apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\Users\jay\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\jay\IdeaProjects\raglette --file=c:\Users\jay\IdeaProjects\raglette\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: ollama
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ollama
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: c:\Users\jay\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\jay\IdeaProjects\raglette --file=c:\Users\jay\IdeaProjects\raglette\docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/raglette-default: "true"
        io.kompose.service: ollama
    spec:
      containers:
        - args:
            - serve
          image: ollama/ollama
          livenessProbe:
            exec:
              command:
                - ollama --version || exit 1
          name: ollama
          ports:
            - containerPort: 11434
              hostPort: 11434
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama
      restartPolicy: Always
      volumes:
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama
status: {}
