apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\Users\jay\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\jay\IdeaProjects\raglette --file=c:\Users\jay\IdeaProjects\raglette\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: tika
  name: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tika
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\Users\jay\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\jay\IdeaProjects\raglette --file=c:\Users\jay\IdeaProjects\raglette\docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/raglette-default: "true"
        io.kompose.service: tika
    spec:
      containers:
        - image: logicalspark/docker-tikaserver:latest
          name: tika
          ports:
            - containerPort: 9998
              hostPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
