apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\Users\jay\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\jay\IdeaProjects\raglette --file=c:\Users\jay\IdeaProjects\raglette\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: webui
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: c:\Users\jay\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\jay\IdeaProjects\raglette --file=c:\Users\jay\IdeaProjects\raglette\docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/raglette-default: "true"
        io.kompose.service: webui
    spec:
      containers:
        - env:
            - name: OLLAMA_BASE_URL
              value: http://host.docker.internal:11434
          image: ghcr.io/open-webui/open-webui:main
          name: open-webui
          ports:
            - containerPort: 8080
              hostPort: 3000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/backend/data
              name: open-webui
      restartPolicy: Always
      volumes:
        - name: open-webui
          persistentVolumeClaim:
            claimName: open-webui
status: {}
