apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\Users\jay\AppData\Roaming\Code\User\globalStorage\othy1010.kompose\kompose.exe convert --out=c:\Users\jay\IdeaProjects\raglette --file=c:\Users\jay\IdeaProjects\raglette\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: webui
  name: webui
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 8080
  selector:
    io.kompose.service: webui
status:
  loadBalancer: {}
